paths:
  /projects:
    get:
      summary: Get a list of projects
      description: Retrieve a list of all projects.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
    post:
      summary: Create a new Project
      description: Create a new Project with the provided data.
      requestBody:
        required: true
        content:
          application/json:
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:

  /projects/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: ID of the Project to retrieve or update
    get:
      summary: Get a Project by ID
      description: Retrieve a Project by their ID.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
        '404':
          description: User not found
    put:
      summary: Update a Project by ID
      description: Update a Project's information by their ID.
      requestBody:
        required: true
        content:
          application/json:
      responses:
        '200':
          description: Project updated successfully
          content:
            application/json:
        '404':
          description: Project not found
    delete:
      summary: Delete a Project by ID
      description: Delete a Project by their ID.
      responses:
        '204':
          description: Project deleted successfully
        '404':
          description: Project not found